#!/usr/bin/env python3
"""Generate the Codex CLI entry file (AGENTS.md) for every skill.

Codex looks for `AGENTS.md` where Claude Code and opencode look for `SKILL.md`,
and it does not inline markdown imports (openai/codex#17401), so it cannot
simply be pointed at the other file.

**What this generates is a POINTER, not a condensed mirror.** The convention
elsewhere in this author's skills is a hand-written AGENTS.md that restates the
protocol in condensed form and is self-sufficient. That is better, and it is
also 22 documents of real writing. A pointer is honest and functional in the
meantime: Codex can read `SKILL.md` with its file-read tool, and the generated
file says plainly that it must. Replace any of these with a hand-written mirror
whenever a skill earns the effort; this script skips files it did not write.

Usage:
    python3 scripts/build_agents_md.py            # write missing AGENTS.md
    python3 scripts/build_agents_md.py --check    # exit 1 if any are missing or stale
    python3 scripts/build_agents_md.py --force    # rewrite generated ones too
"""

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS = REPO / "skills"

# Written into every generated file. Its absence is how a hand-written mirror is
# recognised and left alone.
MARKER = "<!-- generated by scripts/build_agents_md.py; delete this line if you hand-write this file -->"


def frontmatter(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    try:
        block = text.split("---", 2)[1]
    except IndexError:
        return {}
    out, key, buf = {}, None, []
    for line in block.splitlines():
        m = re.match(r"^(\w[\w-]*):\s*(.*)$", line)
        if m:
            if key:
                out[key] = " ".join(buf).strip()
            key, rest = m.group(1), m.group(2).strip()
            buf = [] if rest in (">-", ">", "|", "|-") else [rest]
        elif key and line.strip():
            buf.append(line.strip())
    if key:
        out[key] = " ".join(buf).strip()
    return out


def inventory(skill: Path) -> list[str]:
    """The subdirectories a Codex session will want to know exist."""
    out = []
    for d in sorted(p for p in skill.iterdir() if p.is_dir()):
        n = len([f for f in d.rglob("*") if f.is_file()])
        if n:
            out.append(f"- `{d.name}/` ({n} file{'s' if n > 1 else ''})")
    return out


def render(skill: Path, fm: dict) -> str:
    name = fm.get("name", skill.name)
    desc = fm.get("description", "").strip()
    lines = [
        MARKER,
        "",
        f"# {name} (Codex CLI entry)",
        "",
        "This is the Codex entry point for the FUSION "
        f"`{name}` skill. **It is a pointer, not the skill.** The full protocol, "
        "including every rule, failure mode and verified example, is in "
        "`SKILL.md` next to this file.",
        "",
        "Codex does not inline markdown imports "
        "([openai/codex#17401](https://github.com/openai/codex/issues/17401)), so "
        "nothing below is a substitute for reading it. **Read `SKILL.md` with your "
        "file-read tool before acting on this skill**, and do not answer from this "
        "summary alone.",
        "",
        "## When this skill applies",
        "",
        desc or "(no description in SKILL.md)",
        "",
        "## What is in this directory",
        "",
        "- `SKILL.md`, the full protocol. Read this first.",
    ]
    lines += inventory(skill)
    lines += [
        "",
        "## Scope",
        "",
        "This skill is part of FUSION and carries its rules: reproduce a published "
        "result where one exists, state the benchmark tier honestly, and never "
        "report a calculation as verified on the strength of a run that merely "
        "exited zero.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    if not SKILLS.is_dir():
        sys.exit(f"no skills directory at {SKILLS}")

    wrote, kept, stale = [], [], []
    for skill in sorted(p for p in SKILLS.iterdir() if p.is_dir()):
        src = skill / "SKILL.md"
        if not src.exists():
            continue
        dest = skill / "AGENTS.md"
        want = render(skill, frontmatter(src.read_text(errors="replace")))

        if dest.exists():
            current = dest.read_text(errors="replace")
            if MARKER not in current and not args.force:
                kept.append(skill.name)      # hand-written, leave it alone
                continue
            if current == want:
                continue
            stale.append(skill.name)
        if args.check:
            continue
        dest.write_text(want)
        wrote.append(skill.name)

    if args.check:
        missing = [s.name for s in sorted(p for p in SKILLS.iterdir() if p.is_dir())
                   if (s / "SKILL.md").exists() and not (s / "AGENTS.md").exists()]
        if missing or stale:
            sys.exit(f"AGENTS.md missing for {missing or 'none'}, stale for {stale or 'none'}; "
                     "run scripts/build_agents_md.py")
        print("every skill has a current AGENTS.md")
        return

    print(f"wrote {len(wrote)} AGENTS.md" + (f", left {len(kept)} hand-written alone" if kept else ""))
    if kept:
        print("  hand-written, untouched: " + ", ".join(kept))


if __name__ == "__main__":
    main()
